### ISSUE TITLE
通过字典name返回字典内容。如果字典名字名字含有重复部分，总是返回其中一个。

### ISSUE THREAD

**Issue by Megic** [suyuan32/simple-admin-core#111]
![image](https://github.com/suyuan32/simple-admin-core/assets/1814522/34c6349e-5907-48e5-b1f4-50694a6cb8ac)
见了两个字典，一个名字DrugType，一个名字NonDrugType，都是返回了最后提交的NonDrugType的字典内容！

**Comment by Megic** [comment]
应该是通过name查询的时候用了模糊查询？

**Comment by suyuan32** [comment]
已修复 #112 @Megic
