### ISSUE TITLE
添加菜单报错

### ISSUE THREAD

**Issue by yeaze** [suyuan32/simple-admin-core#131]
按照文档在本地搭建完环境后，项目可以成功运行，但是添加菜单会报错：
![image](https://github.com/suyuan32/simple-admin-core/assets/36060454/e28ea840-2c3a-4d9e-92e0-67c2dd004c59)

**Comment by suyuan32** [comment]
好的，会修复下，建议直接接入 Core 服务即可，因为近期改动较大可能有bug，可以先使用旧的镜像

**Comment by suyuan32** [comment]
【SimpleAdmin实战开发-接入CORE服务】 https://www.bilibili.com/video/BV1do4y1g7VL/?share_source=copy_web&vd_source=f045c6cd68640dbfa7188638af9c7b03

**Comment by suyuan32** [comment]
https://github.com/suyuan32/simple-admin-core/pull/132

**Comment by suyuan32** [comment]
已修复
