### ISSUE TITLE
Separate JWT authentication for app and admin users

### ISSUE THREAD

**Issue by cgc1983** [suyuan32/simple-admin-core#207]
I'm currently working with your open-source project and I noticed that it only has an admin panel. I would like to contribute by adding an app module to the project. The framework is currently using JWT for user authentication. However, I believe it would be beneficial to have separate JWT authentication for app users and admin users.

Can you guide me on how to implement this separation of JWT authentication for the app and admin users? I would appreciate any advice or recommendations on the best approach to achieve this.

Thank you for your attention and I look forward to your response.

**Comment by suyuan32** [comment]
You can use MMS (Member management service ) to do that.
