### ISSUE TITLE
关于validator的一些优化

### ISSUE THREAD

**Issue by waltcow** [suyuan32/simple-admin-core#23]
一般的accept-language是这样的
```
accept-language: zh,en;q=0.9,en-US;q=0.8,zh-CN;q=0.7,zh-TW;q=0.6,la;q=0.5,ja;q=0.4,id;q=0.3,fr;q=0.2
```
下面的这段 在validate时， translate估计只能fallback到en了

https://github.com/suyuan32/simple-admin-tools/blob/f9473c481b9ae1c3f7e3a428314be3fce4760909/rest/httpx/requests.go#L48-L56

建议parse accept-language header时可以参考这里

https://github.com/nicksnyder/go-i18n/blob/639caa7eb5031c3fc275d5b3bf1f44fe3c3f2623/v2/i18n/localizer.go#L30-L51

还有就是在RegisterDefaultTranslation 失败的error类型不应是类似`RegisterDefaultTranslationsError` 吗?
为啥要抛出`DatabaseError` ?
还有作为 **gozero** 为何要引用回你的core-admin 的error代码？

```golang
	err := en_translations.RegisterDefaultTranslations(v.Validator, enTrans)
	if err != nil {
		logx.Errorw(logmessage.DatabaseError, logx.Field("Detail", err.Error()))
		return nil
	}
	err = zh_translations.RegisterDefaultTranslations(v.Validator, zhTrans)
	if err != nil {
		logx.Errorw(logmessage.DatabaseError, logx.Field("Detail", err.Error()))
		return nil
	}
```

**Comment by suyuan32** [comment]
那个logmessage 是之前测试时候粘过去的，应该改一下，其实就是log信息的字符串而已。至于 parseTags 这个方法之前并不知道，是一个可以优化的点，之前主要是针对 vben 开发的，所以accept-language 并没有考虑比较细致，只针对了axios的请求语言进行了设计，欢迎提交PR :)

**Comment by suyuan32** [comment]
第一版tool有部分引用到core里面的内容，这些引用后续删掉了一些，没有完全清理干净，需要全部移除

**Comment by suyuan32** [comment]
log message 已删除， parseTags 我再看下怎么接入先

**Comment by suyuan32** [comment]
@waltcow

**Comment by suyuan32** [comment]
已添加 ParseAcceptLanguage 函数进行处理
