### ISSUE TITLE
初始化数据库文档太模糊了

### ISSUE THREAD

**Issue by bellingham07** [suyuan32/simple-admin-core#249]
![image](https://github.com/suyuan32/simple-admin-core/assets/93235908/3da13e5d-4851-4613-bc3d-24c78936c5ff)
这描述有点模糊，感觉和上下文没有联系，我把所有项目都跑起来了，就是进不去这个init页面

**Comment by suyuan32** [comment]
看视频教程

**Comment by wuchencm** [comment]
> 看视频教程

![image](https://github.com/user-attachments/assets/f1d7542a-ed1b-44f6-97df-e8ad423c4cee)
同样访问不了
