### ISSUE TITLE
第二次新增菜单的目录类型报数据冲突

### ISSUE THREAD

**Issue by zhang00829** [suyuan32/simple-admin-core#267]
**Describe the bug**
![image](https://github.com/suyuan32/simple-admin-core/assets/40270286/140c7578-70c5-486a-802c-6f3ea25311bd)

**To Reproduce**
1. 先新增一个目录类型，会成功
2. 再新增一个目录类型，会报数据冲突

**原因分析**
+ 新增目录类型默认将path设置为空字符串
![image](https://github.com/suyuan32/simple-admin-core/assets/40270286/2ceea0d3-385c-4068-bb48-9d064eaa8373)
+ 数据库中path又有唯一索引要求
![image](https://github.com/suyuan32/simple-admin-core/assets/40270286/2842b426-8af5-474e-b924-3526b11b7afc)

导致第二次新增path为空与数据库前一条为空的path冲突

**Comment by suyuan32** [comment]
目录的 Path 不能为空，可能会导致前端路由异常

**Comment by zhang00829** [comment]
> 目录的 Path 不能为空，可能会导致前端路由异常

感谢回复🙏
但截图中设置path为空字符串的代码 就是现在simple-admin-core的master分支的代码。所以是否是bug，还是有其他特殊的需求，希望作者大大不吝赐教😄

**Comment by suyuan32** [comment]
> > 目录的 Path 不能为空，可能会导致前端路由异常
> 
> 感谢回复🙏 但截图中设置path为空字符串的代码 就是现在simple-admin-core的master分支的代码。所以是否是bug，还是有其他特殊的需求，希望作者大大不吝赐教😄

对，已修复 #268
