### ISSUE TITLE
base64Captcha v1.3.6的bug导致simple-admin所有可选验证码的场景验证码可绕过

### ISSUE THREAD

**Issue by aac3476** [suyuan32/simple-admin-core#270]
例如：[https://github.com/suyuan32/simple-admin-member-api/blob/6cceafa1077fc3f921fb24f7ce596e3bb894f573/internal/logic/publicmember/login_logic.go#L48](https://github.com/suyuan32/simple-admin-member-api/blob/6cceafa1077fc3f921fb24f7ce596e3bb894f573/internal/logic/publicmember/login_logic.go#L48)

开关失效 可以通过传空验证码信息绕过验证码验证

相关问题链接
[https://github.com/mojocn/base64Captcha/issues/122](https://github.com/mojocn/base64Captcha/issues/122)

建议降级base64Captcha版本

**Comment by suyuan32** [comment]
api不是有校验不能为空嘛

**Comment by suyuan32** [comment]
![image](https://github.com/suyuan32/simple-admin-core/assets/21239039/dea234eb-a137-43ca-8886-012345241185)

**Comment by suyuan32** [comment]
好吧omitempty 了

**Comment by suyuan32** [comment]
已修复 https://github.com/suyuan32/base64Captcha/releases/tag/v1.3.7

**Comment by aac3476** [comment]
> 已修复 https://github.com/suyuan32/base64Captcha/releases/tag/v1.3.7

效率
