### ISSUE TITLE
swagger 注解的优化

### ISSUE THREAD

**Issue by waltcow** [suyuan32/simple-admin-core#28]
```golang
    // swagger:route DELETE /user user deleteUser
    // Delete user information | 删除用户信息
    // Parameters:
    //  + name: body
    //    require: true
    //    in: body
    //    type: IDReq
    // Responses:
    //   200: SimpleMsg
    //   401: SimpleMsg
    //   500: SimpleMsg
    @handler deleteUser
    delete /user (IDReq) returns (SimpleMsg)
```

现在感觉api文件过于重复显得臃肿。
如果结合 [gozero api](https://go-zero.dev/cn/docs/design/grammar/) 已有语法 `@doc`，
可以删减一些重复的定义， 譬如 `    // swagger:route DELETE /user user deleteUser`
在api文件parse的过程中，应该可以推出类似的swagger 路由信息

**Comment by suyuan32** [comment]
你这个只是需要改下生成逻辑，但是我觉得拆分出来就会被定死了，有些用户要有多个tag或者别名怎么弄？直接集成go-swagger默认的注解感觉好一点

**Comment by waltcow** [comment]
好吧，让我再想想👀

**Comment by waltcow** [comment]
@suyuan32 

稍微diy了一下
https://github.com/go-slash/go-zero-enhanced/commit/f6ab4f83f0dd63b9133380b6c8296f156973a19f

```
    @doc(
        summary: "Update user's profile | 更新用户个人信息"
        description: "更新用户个人信息"
    )
    @handler updateUserProfile
    post /user/profile (ProfileReq) returns (SimpleMsg)
```

==>

```
// swagger:route post /user/profile user UpdateUserProfile
//
// "Update user's profile | 更新用户个人信息"
//
// "更新用户个人信息"
//
// Parameters:
//  + name: body
//    require: true
//    in: body
//    type: ProfileReq
//
//
// Responses:
//  200: SimpleMsg
//
//
```

**Comment by suyuan32** [comment]
看起来可以，你修改完善点提交PR给我测试下，注意要把API文件也改了

**Comment by suyuan32** [comment]
@waltcow

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/197790074-8e7cb274-3141-42dd-9d57-c6cb6b70af96.png)
注意有些是没有 parameters 的

**Comment by suyuan32** [comment]
还有就是需要多运行 goctls doc命令嘛？

**Comment by suyuan32** [comment]
https://goswagger.io/use/spec/route.html

**Comment by waltcow** [comment]
> 看起来可以，你修改完善点提交PR给我测试下，注意要把API文件也改了

明天我再完善一下，把genStruct的注解生成也处理了

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/197792887-2fc19223-bf57-457e-9c2f-b27e5b249b1e.png)
![image](https://user-images.githubusercontent.com/21239039/197793238-e694e7c9-51ce-4b3c-b5bd-7f124c929801.png)
还有就是结构体的注解也需要解析

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/197793491-059480b7-d040-4dc4-8f61-bcc7134c45da.png)

**Comment by suyuan32** [comment]
生成代码会简洁些，后续用户要自己定制的话得自己去handler修改，不过可以少写很多注释，效率应该高些

**Comment by suyuan32** [comment]
@waltcow  注解生成弄得咋样了，我准备升级下goctl, 文件名以后还是采用下划线吧，之前用的是默认的文件名，太难分辨了，原来还有 style参数可选的，没注意

**Comment by waltcow** [comment]
@suyuan32 

https://github.com/go-slash/go-zero-enhanced
我的Fork也参考你的做了类似的修改，但没把`GORM`，`Casbin`， `Consul`的东西集成

在 `goctls api go` cli 中加入`--swagger` 开启swagger注解生成, 把**swagger**的注解加入进去，

人为的把`Resp`, `Req` 结尾的struct 归类成`swagger:response` 和 `swagger:model`

现在用着还可以

**Comment by waltcow** [comment]
https://github.com/zeromicro/go-zero/pull/2528

@suyuan32 最近看了下这个PR，感觉在验证和openapi doc生成上可以做的更优雅

**Comment by suyuan32** [comment]
改了好多呀，主要区别是啥？有没有生成的文件看下效果？

**Comment by suyuan32** [comment]
@waltcow

**Comment by waltcow** [comment]
> 改了好多呀，主要区别是啥？有没有生成的文件看下效果？

主要是不用生成swagger 的annotations.直接扩充了api的spec和parse 结果，再生成openapi doc

**Comment by suyuan32** [comment]
简单看了下，不是很清楚好在哪。。。

openapi 和 swagger 的配置文件有啥区别？也没有示例文档介绍

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/199152361-1d9bf0b6-0e10-495b-b98e-fdbe14bbdb8b.png)
他通过定义注释的标签来实现？

**Comment by suyuan32** [comment]
这些 go-swagger 不是已经实现了嘛 @waltcow

**Comment by suyuan32** [comment]
看起来重复造轮子了

**Comment by suyuan32** [comment]
目前来说也就是 response 和 model需要 annotations, route现在已经生成好了，他只是将 go-swagger 的功能集成到 goctl中，好处是不需要文件里有注释？

**Comment by waltcow** [comment]
> 目前来说也就是 response 和 model需要 annotations, route现在已经生成好了，他只是将 go-swagger 的功能集成到 goctl中，好处是不需要文件里有注释？

是的，无需再次用go swagger 再去提取doc 再生成apidoc

**Comment by suyuan32** [comment]
但是感觉也没少写多少，多于注释来说，只是文件里面没有了注解，还有就是少运行一条命令，考虑考虑，因为他的validator啥的都是自己实现的，实际上handler和type里面多了好多validate

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/199154274-47a577d4-0910-411d-beab-30e2754c61a1.png)

**Comment by suyuan32** [comment]
没搞懂为啥要自己实现validator

**Comment by suyuan32** [comment]
playground 里面不是已经实现了嘛，国际化他这个不支持

**Comment by suyuan32** [comment]
我的框架有外国人用的，尽量支持多语言

**Comment by suyuan32** [comment]
他只支持英文返回

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/199154783-0335c7e4-699b-4204-97f0-684481aa933a.png)

**Comment by suyuan32** [comment]
支持的种类也不如 https://github.com/go-playground/validator

**Comment by suyuan32** [comment]
是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...

**Comment by suyuan32** [comment]
@waltcow

**Comment by waltcow** [comment]
> 是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...

我再仔细看完PR修改
发现只是用**openapi** doc 生成 **api**文件，和我刚开始的想象不太一样😭

**Comment by ddzrc** [comment]
> > 是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...
> 
> 我再仔细看完PR修改 发现只是用**openapi** doc 生成 **api**文件，和我刚开始的想象不太一样sob

能通过解析 openapi2.0/3.0 文档生成脚手架代码，没有生成.api 文件

**Comment by ddzrc** [comment]
> 是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...

swagger/ openapi 中可以 定义参数校验， 不需要定义注解

**Comment by ddzrc** [comment]
> 没搞懂为啥要自己实现validator

当时考虑过， go-zero自带的校验， 和https://github.com/go-playground/validator， openapi 的校验功能比 go-zero 要多很多，go-playground 主要考虑到性能损耗也放弃了

**Comment by suyuan32** [comment]
> > > 是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...
> > 
> > 
> > 我再仔细看完PR修改 发现只是用**openapi** doc 生成 **api**文件，和我刚开始的想象不太一样sob
> 
> 能通过解析 openapi2.0/3.0 文档生成脚手架代码，没有生成.api 文件

openapi 文档前端提供？和写api有啥区别，感觉和官方不兼容，openapi生成的代码api文件里没有，感觉只能二选一，优点可能是openapi 可以使用软件可视化生成？go-playground 需要解析tag性能是会有损耗，看接口需求吧。考虑性能的话框架不能太重，考虑功能丰富的话性能又难满足.

**Comment by suyuan32** [comment]
而且有点难维护，validator代码改一下就得重新生成一次工具 @ddzrc

**Comment by suyuan32** [comment]
而且有点难维护，validator代码改一下就得重新生成一次工具 @ddzrc

**Comment by ddzrc** [comment]
> > > > 是通过 一个注解同时生成了 swagger 和 validator的代码，也意味着需要自己维护swagger 和 validator ...
> > > 
> > > 
> > > 我再仔细看完PR修改 发现只是用**openapi** doc 生成 **api**文件，和我刚开始的想象不太一样sob
> > 
> > 
> > 能通过解析 openapi2.0/3.0 文档生成脚手架代码，没有生成.api 文件
> 
> openapi 文档前端提供？和写api有啥区别，感觉和官方不兼容，openapi生成的代码api文件里没有，感觉只能二选一，优点可能是openapi 可以使用软件可视化生成？go-playground 需要解析tag性能是会有损耗，看接口需求吧。考虑性能的话框架不能太重，考虑功能丰富的话性能又难满足.

一般来说谁提供接口，谁提供 openapi/swagger 文档， 相比官方解析 .api文件，只多了出参和入参 的 validate 方法，其他都一致

**Comment by ddzrc** [comment]
> 而且有点难维护，validator代码改一下就得重新生成一次工具

这个 swagger/openapi 注重对接，是从文档到代码， 而不是先修改代码，再修改文档

**Comment by suyuan32** [comment]
看不同需求吧，我们这边是通过api生成swagger, 官方的态度是api基本就是文档的功能，如果需要添加额外定制的话只能自己fork修改使用，你写的功能属于增加了新的解析功能，感觉官方比较难采纳，你这个的好处我感觉是前端方便了，前端直接编写api给后端使用，go zero反过来是后端写好接口给前端调用，对接来说是快了些，但前提是前端文档设计要合理，不然字段啥的设计不符合后端要求的话也麻烦

**Comment by suyuan32** [comment]
对前端的要求高了

**Comment by suyuan32** [comment]
文档不合理的话后端只能干着急了

**Comment by ddzrc** [comment]
> 但前提是前端文档设计要合理，不然字段啥的设计不符合后端要求的话也麻烦

谁写文档的话，看业务，和团队吧， 我见过很多公司，是后来写文档， 不过 open/swagger 编写的成本确实很高

**Comment by waltcow** [comment]
通过扩展API的语法，生成项目脚手架 和 `OpenAPI` 接口定义，我觉得这样比较简单点 @suyuan32 @ddzrc

**Comment by crazy6995** [comment]
对于routes的parameters，目前是定义为

```
Parameters:
  + name: body
     required: true
     in: query
     type: OauthLoginReq
```

想问一个问题，就是我有一个 `get /oauth/login oauthprovider OauthLogin`

参数放置于 query 中，如何才能在 `swagger` 中将`query`（也即是 `form`）展现出来并测试请求呢？

是不是需要手动将 `OauthLoginReq` 拆解，并写为多个 `parameters`，然后修改 handler 中的注释吗？

**Comment by suyuan32** [comment]
> 对于routes的parameters，目前是定义为
> 
> ```
> Parameters:
>   + name: body
>      required: true
>      in: query
>      type: OauthLoginReq
> ```
> 
> 想问一个问题，就是我有一个 `get /oauth/login oauthprovider OauthLogin`
> 
> 参数放置于 query 中，如何才能在 `swagger` 中将`query`（也即是 `form`）展现出来并测试请求呢？
> 
> 是不是需要手动将 `OauthLoginReq` 拆解，并写为多个 `parameters`，然后修改 handler 中的注释吗？
> 
> 简单点说，就是如何支持 `query(form)` 参数 / `path`参数 / `header`参数 的 swagger 文档生成？
> 
> 不是很懂。。 我看 genhandlers 中并没有收集到所有的信息，不知道怎么去实现。

https://goswagger.io/use/spec/route.html

**Comment by suyuan32** [comment]
> > 对于routes的parameters，目前是定义为
> > ```
> > Parameters:
> >   + name: body
> >      required: true
> >      in: query
> >      type: OauthLoginReq
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 想问一个问题，就是我有一个 `get /oauth/login oauthprovider OauthLogin`
> > 参数放置于 query 中，如何才能在 `swagger` 中将`query`（也即是 `form`）展现出来并测试请求呢？
> > 是不是需要手动将 `OauthLoginReq` 拆解，并写为多个 `parameters`，然后修改 handler 中的注释吗？
> > 简单点说，就是如何支持 `query(form)` 参数 / `path`参数 / `header`参数 的 swagger 文档生成？
> > 不是很懂。。 我看 genhandlers 中并没有收集到所有的信息，不知道怎么去实现。
> 
> https://goswagger.io/use/spec/route.html

https://goswagger.io/use/spec/params.html

**Comment by suyuan32** [comment]
> > > 对于routes的parameters，目前是定义为
> > > ```
> > > Parameters:
> > >   + name: body
> > >      required: true
> > >      in: query
> > >      type: OauthLoginReq
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 想问一个问题，就是我有一个 `get /oauth/login oauthprovider OauthLogin`
> > > 参数放置于 query 中，如何才能在 `swagger` 中将`query`（也即是 `form`）展现出来并测试请求呢？
> > > 是不是需要手动将 `OauthLoginReq` 拆解，并写为多个 `parameters`，然后修改 handler 中的注释吗？
> > > 简单点说，就是如何支持 `query(form)` 参数 / `path`参数 / `header`参数 的 swagger 文档生成？
> > > 不是很懂。。 我看 genhandlers 中并没有收集到所有的信息，不知道怎么去实现。
> > 
> > 
> > https://goswagger.io/use/spec/route.html
> 
> https://goswagger.io/use/spec/params.html

form好像是用 parameter， path的例子我有空补一下 @crazy6995

**Comment by crazy6995** [comment]
了解，我使用

`goctls api plugin -plugin goctl-swagger="swagger -filename core.json" -api ./api/desc/oauth_provider.api --dir ./`

可以正常生成需要的 `parameters` ，但是官方插件是基于 api 文件去做的，咱这边是基于已生成的 .go 文件，通过文件中的注释来使用的，也就是 go-swagger 的标准用法。

如最上那个朋友所说，如果使用 atDoc 是不是会更加舒服一些，基于 plugins 的方式，可能只需要在 api 文件中打磨注释，也就是打磨了api文档

**Comment by crazy6995** [comment]
> > > > 对于routes的parameters，目前是定义为
> > > > ```
> > > > Parameters:
> > > >   + name: body
> > > >      required: true
> > > >      in: query
> > > >      type: OauthLoginReq
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 想问一个问题，就是我有一个 `get /oauth/login oauthprovider OauthLogin`
> > > > 参数放置于 query 中，如何才能在 `swagger` 中将`query`（也即是 `form`）展现出来并测试请求呢？
> > > > 是不是需要手动将 `OauthLoginReq` 拆解，并写为多个 `parameters`，然后修改 handler 中的注释吗？
> > > > 简单点说，就是如何支持 `query(form)` 参数 / `path`参数 / `header`参数 的 swagger 文档生成？
> > > > 不是很懂。。 我看 genhandlers 中并没有收集到所有的信息，不知道怎么去实现。
> > > 
> > > 
> > > https://goswagger.io/use/spec/route.html
> > 
> > 
> > https://goswagger.io/use/spec/params.html
> 
> form好像是用 parameter， path的例子我有空补一下 @crazy6995

我试试看。

**Comment by suyuan32** [comment]
https://github.com/go-swagger/go-swagger/blob/54644101dc9870a16814f8b18d0cb99e33619a17/fixtures/goparsing/classification/operations/noparams.go#L131

**Comment by suyuan32** [comment]
atDoc 好多参数不支持，扩展起来比较麻烦，实际上并不简单多少

**Comment by suyuan32** [comment]
实际上go swagger的注释也可以全部写在 api里的，如果想写的话，直接把 handler 上面的注释粘到 handler 方即可

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/228715507-a1716b68-9fe6-44e6-85a3-5b270a11428f.png)

**Comment by suyuan32** [comment]
我看了下，好像现在不行，我加下代码吧，之前就是直接写在头上，然后改进成一行注释了，得加语句判断下

**Comment by crazy6995** [comment]
> ![image](https://user-images.githubusercontent.com/21239039/228715507-a1716b68-9fe6-44e6-85a3-5b270a11428f.png)

了解，但是这样的话，我每一个 request 参数都需要自己写 Parameters 。。 emmm  我看官方倒是能生成 带有 parameters 的 yaml，我也看了一下代码，似乎默认都使用了 body 作为 name

**Comment by suyuan32** [comment]
因为handler改动频率不太高，所以选择放在handler里，一共就三种，只需改in: path, in: query, in: body

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/228718125-9daac86f-a1d6-4444-b5c3-242e49d3a3f7.png)

**Comment by crazy6995** [comment]
我还是用不起来 `swagger:parameters `

可有使用示例？  

我看框架上目前都是使用  post 方法，post的参数放在body，`go-swagger`会自动使用definitions的schema，而好像`parameters`需要解构，倒是还没搞懂。

**Comment by crazy6995** [comment]
> 我还是用不起来 `swagger:parameters `
> 
> 可有使用示例？
> 
> 我看框架上目前都是使用 post 方法，post的参数放在body，`go-swagger`会自动使用definitions的schema，而好像`parameters`需要解构，倒是还没搞懂。

刚刚说完，就又去尝试了一下，目前正常了。

**Comment by suyuan32** [comment]
https://github.com/suyuan32/simple-admin-file/blob/master/api/internal/handler/file/download_file_handler.go

**Comment by crazy6995** [comment]
![image](https://user-images.githubusercontent.com/5605020/228719880-be790cee-e637-4ba3-bcef-c489b93697cb.png)
![image](https://user-images.githubusercontent.com/5605020/228719992-b270e36e-12c2-4904-8fd1-39554b7840b1.png)

**Comment by suyuan32** [comment]
> ![image](https://user-images.githubusercontent.com/5605020/228719880-be790cee-e637-4ba3-bcef-c489b93697cb.png) ![image](https://user-images.githubusercontent.com/5605020/228719992-b270e36e-12c2-4904-8fd1-39554b7840b1.png)

我看看

**Comment by suyuan32** [comment]
第一和第三都是go swagger的格式要求，第二个可以修复下

> 说一下刚刚遇到的坑
> 
> * 若使用 swagger:parameters，那么需要保证 [operationId] 要与 @handler handlerName 相同，否则无法自动解构struct到parameters
> * 对于参数在query(form)的请求，genhandlers的生成会多出一个 Paramters ，其实是不需要的。
> * 不知道为什么`go-swagger`不允许同一个struct具有多个特性，比方说它不允许 `swagger:model`与`swagger:parameter` 同时使用，不知道是基于什么考量。有一些奇葩设计的接口就是参数一致，但一个走 query 一个走 form，当然 go-zero 也是不支持 `json`与`form` 混用的。

**Comment by crazy6995** [comment]
> 第一和第三都是go swagger的格式要求，第二个可以修复下
> 
> > 说一下刚刚遇到的坑
> > 
> > * 若使用 swagger:parameters，那么需要保证 [operationId] 要与 @handler handlerName 相同，否则无法自动解构struct到parameters
> > * 对于参数在query(form)的请求，genhandlers的生成会多出一个 Paramters ，其实是不需要的。
> > * 不知道为什么`go-swagger`不允许同一个struct具有多个特性，比方说它不允许 `swagger:model`与`swagger:parameter` 同时使用，不知道是基于什么考量。有一些奇葩设计的接口就是参数一致，但一个走 query 一个走 form，当然 go-zero 也是不支持 `json`与`form` 混用的。

是的，那是我不够了解导致的坑，在这记录一下，以便后续人员可以查看。 emoji:cry
第二条和path的内容可以调整一下。

**Comment by suyuan32** [comment]
swagger 文档已更新 https://doc.ryansu.pro/zh/guide/feature/swagger.html @crazy6995 已支持 path 和 query
