### ISSUE TITLE
登陆的时候报401 是什么原因？

### ISSUE THREAD

**Issue by wensenz** [suyuan32/simple-admin-core#3]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/10190672/192077449-ce7f4421-d59e-4c98-a8ea-fba013aadb5f.png">

**Comment by suyuan32** [comment]
先初始化数据库

**Comment by suyuan32** [comment]
访问网址 https://address:port/#/init

**Comment by wensenz** [comment]
初始化了， 注册是成功的

**Comment by suyuan32** [comment]
然后需要重启 rpc 和 api

**Comment by suyuan32** [comment]
因为未初始化gorm会卡在找不到表

**Comment by wensenz** [comment]
我初始化“文件管理数据库初始化”超时了的， 注册账号入口了。登陆还是401，

**Comment by suyuan32** [comment]
那个是可选项目，不一定要运行，那个需要运行 simple-admin-file

**Comment by wensenz** [comment]
那我还少了什么吗？ admin的初始密码是什么？ 我试下admin能不能登陆

**Comment by suyuan32** [comment]
查看一下 casbin_rule表，这个问题我也出现过，就是casbin读取数据库太慢，等一下再重启rpc和api

**Comment by suyuan32** [comment]
账号 admin
密码 simple-admin

**Comment by wensenz** [comment]
admin，登陆成功了， 我自己新注册的号登不上， 这个账号是我初始化数据库后直接（未重启rpc、api）注册的。 是不是这原因导致的？

**Comment by suyuan32** [comment]
是的

**Comment by suyuan32** [comment]
重新注册下

**Comment by wensenz** [comment]
提交个BUG， 后台删除用户后，
<img width="740" alt="image" src="https://user-images.githubusercontent.com/10190672/192078094-1cc77f2e-f54b-493d-ab0c-25805bfb51de.png">
再次注册同名用户的时候提示：Error 1062: Duplicate entry 'wensenz' for key 'users.username'
<img width="726" alt="image" src="https://user-images.githubusercontent.com/10190672/192078112-dd20a93a-1139-4b01-9717-5cf704f6ef8f.png">

**Comment by suyuan32** [comment]
是的，软删除是这样的

**Comment by suyuan32** [comment]
可以改下

**Comment by suyuan32** [comment]
其实这也可以方便你恢复

**Comment by suyuan32** [comment]
直接设为null就可以恢复账号

**Comment by wensenz** [comment]
重新注册后的账号， 还是无法登陆

**Comment by suyuan32** [comment]
默认注册角色是注册会员，需要修改角色

**Comment by suyuan32** [comment]
注册会员没有后台权限

**Comment by suyuan32** [comment]
修改角色或者给角色添加权限

**Comment by wensenz** [comment]
嗯， 破案了， 是不是可以吧admin账号密码更新到 md？ 我没有在文档中看到这个

**Comment by suyuan32** [comment]
文档有的，现在正在更新新的文档，会更完善
