### ISSUE TITLE
make gen-rpc失败 'optional' labels are disallowed in the Proto3 syntax

### ISSUE THREAD

**Issue by bendh1** [suyuan32/simple-admin-core#319]
$ make gen-rpc
goctls rpc protoc ./example.proto --go_out=./types --go-grpc_out=./types --zrpc_out=. --style=go_zero
Generating...
Merge proto files successfully
Error: example.proto:89:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.

**Comment by suyuan32** [comment]
升级 protoc
