### ISSUE TITLE
整理字符串的常量

### ISSUE THREAD

**Issue by waltcow** [suyuan32/simple-admin-core#32]
`redis cache key`

```golang
	var apis []model.Api
	check := l.svcCtx.DB.Find(&apis)
	if check.RowsAffected != 0 {
		err := l.svcCtx.Redis.Set("database_init_state", "1")
		if err != nil {
			logx.Errorw(logmessage.RedisError, logx.Field("detail", err.Error()))
			return nil, status.Error(codes.Internal, errorx.RedisError)
		}
		return &core.BaseResp{Msg: errorx.AlreadyInit}, nil
	}

	// set default state value
	l.svcCtx.Redis.Setex("database_error_msg", "", 300)
	l.svcCtx.Redis.Set("database_init_state", "0")

```

`roleId`

```golang

func (l *InitDatabaseLogic) insertRoleMenuAuthorityData() error {
	var menus []model.Menu
	result := l.svcCtx.DB.Find(&menus)
	if result.Error != nil {
		logx.Errorw(logmessage.DatabaseError, logx.Field("detail", result.Error.Error()))
		return status.Error(codes.Internal, result.Error.Error())
	}

	var insertString strings.Builder
	insertString.WriteString("insert into role_menus values ")
	for i := 0; i < len(menus); i++ {
		if i != len(menus)-1 {
			insertString.WriteString(fmt.Sprintf("(%d, %d),", menus[i].ID, 1))
		} else {
			insertString.WriteString(fmt.Sprintf("(%d, %d);", menus[i].ID, 1))
		}
	}
```

**Comment by suyuan32** [comment]
没看懂，什么问题？

**Comment by waltcow** [comment]
一些redis的cache key 譬如`database_init_state`  常量应该收纳到某个package 里面（globalkey）？

**Comment by suyuan32** [comment]
要常量的话直接放在同一个文件下声明啰，我考虑下

**Comment by waltcow** [comment]
还有就是GORM的用法没法做到typesafe, 还有手写一堆的字符串常量，个人认为和直接raw sql 没啥区别

```golang
func (l *SetRoleStatusLogic) SetRoleStatus(in *core.SetStatusReq) (*core.BaseResp, error) {
	result := l.svcCtx.DB.Table("roles").Where("id = ?", in.Id).Update("status", in.Status)
	if result.Error != nil {
		logx.Errorw(logmessage.DatabaseError, logx.Field("detail", result.Error.Error()))
		return nil, status.Error(codes.Internal, result.Error.Error())
	}

```

**Comment by suyuan32** [comment]
个别地方而已吧，update也支持直接传实例呀，看习惯吧，直接写raw肯定麻烦的，比如创建的时候
`
data := &model.Role{
			Model:         gorm.Model{},
			Name:          in.Name,
			Value:         in.Value,
			DefaultRouter: in.DefaultRouter,
			Status:        in.Status,
			Remark:        in.Remark,
			OrderNo:       in.OrderNo,
		}
		result := l.svcCtx.DB.Create(&data)
`

**Comment by suyuan32** [comment]
result := l.svcCtx.DB.Table("roles").Where("id = ?", in.Id).Update("status", in.Status)

如果只说这一句的话的确和sql差不多了

**Comment by waltcow** [comment]
我现在用着的是`ent` , 类似的

```golang
l.svcCtx.EntClient.SysRole.UpdateOneID(req.Id).SetStatus(req.Status).ExecX(l.ctx)
```

**Comment by suyuan32** [comment]
自己写还得考虑注入的问题，参数校验

**Comment by waltcow** [comment]
> 个别地方而已吧，update也支持直接传实例呀，看习惯吧，直接写raw肯定麻烦的，比如创建的时候
> 
> ```
> data := &model.Role{
> 			Model:         gorm.Model{},
> 			Name:          in.Name,
> 			Value:         in.Value,
> 			DefaultRouter: in.DefaultRouter,
> 			Status:        in.Status,
> 			Remark:        in.Remark,
> 			OrderNo:       in.OrderNo,
> 		}
> 		result := l.svcCtx.DB.Create(&data)
> 

这里可以考虑下用`mapstruct`的一些库， 譬如 [goverter](https://github.com/jmattheis/goverter) 

把 `XXXReq`  转换成 ORM 的  `entity`

**Comment by suyuan32** [comment]
> 我现在用着的是`ent` , 类似的
> 
> ```go
> l.svcCtx.EntClient.SysRole.UpdateOneID(req.Id).SetStatus(req.Status).ExecX(l.ctx)
> ```

你这个有点像python的链式, SetStatus 是自动生成的？有点像django的方法

**Comment by suyuan32** [comment]
> 这里可以考虑下用`mapstruct`的一些库， 譬如 [goverter](https://github.com/jmattheis/goverter)
> 
> 把 `XXXReq` 转换成 ORM 的 `entity`

那些只能后续优化了，现在定时任务和消息队列还在进行中，人手不够

**Comment by suyuan32** [comment]
后期还想直接通过数据库表或者model定义文件生成CRUD模板，基本的增删改查自动生成，也要花挺多精力的，希望更多人参与进来贡献代码吧

**Comment by suyuan32** [comment]
gorm毕竟发展比较久，用的人也比较多，bug应该少点吧

**Comment by suyuan32** [comment]
https://gorm.io/docs/update.html#Update-single-column

> result := l.svcCtx.DB.Table("roles").Where("id = ?", in.Id).Update("status", in.Status)
> 
> 如果只说这一句的话的确和sql差不多了

table 可以改成model ，ent封装了where("id =?")       UpdateOneID(req.Id) ，多了一些封装，看自己喜好选择吧，-go-zero官方给的就是基本纯sql

**Comment by suyuan32** [comment]
> 我现在用着的是`ent` , 类似的
> 
> ```go
> l.svcCtx.EntClient.SysRole.UpdateOneID(req.Id).SetStatus(req.Status).ExecX(l.ctx)
> ```

ent 国内好像用的比较少，百度搜不到啥内容，第一次听说，不过看了下也还行

**Comment by waltcow** [comment]
https://github.com/go-slash/slash-admin

这是我最近魔改的，可以对照下 @suyuan32

**Comment by suyuan32** [comment]
尝试了下，感觉ent的确有点东西，原来是代码生成的，我说怎么会有链式方法出来，这样来看的话的确方便，有点django的感觉 @waltcow

**Comment by suyuan32** [comment]
准备弄个分支把gorm替换看看
