### ISSUE TITLE
something wrong with goctls rpc ent command

### ISSUE THREAD

**Issue by aac3476** [suyuan32/simple-admin-core#321]
**Describe the bug**

(base) ➜  simple-admin-core git:(master) ✗ make gen-rpc-ent-logic model=User group=user
goctls rpc ent --schema=./rpc/ent/schema --style=go_zero --import_prefix=/rpc --service_name=Core --project_name=core -o=./rpc --model=User --group=user --i18n=true --proto_out=./rpc/desc/user.proto --overwrite=true
Generating...
Error: entc/load: # command-line-arguments
.entc/entc_github.com_suyuan32_simple-admin-core_rpc_ent_schema_1722419686.go:162:24: fd.Deprecated undefined (type *"entgo.io/ent/schema/field".Descriptor has no field or method Deprecated)
.entc/entc_github.com_suyuan32_simple-admin-core_rpc_ent_schema_1722419686.go:163:24: fd.DeprecatedReason undefined (type *"entgo.io/ent/schema/field".Descriptor has no field or method DeprecatedReason)

**To Reproduce**
1. git clone simple-admin-core
2. run 'make gen-rpc-ent-logic model=User group=user'

**Screenshots**
<img width="1856" alt="image" src="https://github.com/user-attachments/assets/2d5b653b-2419-41fb-9317-2258ff9f373b">

**Desktop (please complete the following information):**
 - OS: Macos with AppleSilicon
 - Go 1.22.5 
 - goctls version v1.8.1 darwin/arm64 - Go Zero v1.7.0 - Simple Admin Tools v1.7.0

<img width="787" alt="image" src="https://github.com/user-attachments/assets/2fa22b45-8cee-4024-94de-45a1f58d2a70">

**Comment by suyuan32** [comment]
upgrade goctls to v1.8.2, new version of ent causes this problem, we had reverted to stable version

**Comment by aac3476** [comment]
> Owner

nice, it works
