### ISSUE TITLE
search_key_num 支持 int64 / Time /uint32 /Bool类型生成 列表搜索字段

### ISSUE THREAD

**Issue by Avey777** [suyuan32/simple-admin-core#326]
goctls rpc ent --search_key_num=100

![image](https://github.com/user-attachments/assets/d58f207d-daeb-4c31-bce1-74b1480158c9)

https://doc.ryansu.tech/zh/guide/quick-start/codegen/rpc_example.html#rpc-ent%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D

**Comment by Avey777** [comment]
最好支持所有 proto 支持的数据类型

**Comment by suyuan32** [comment]
goctls v1.9.3 已支持
