### ISSUE TITLE
关于Ent集成的一些想法

### ISSUE THREAD

**Issue by waltcow** [suyuan32/simple-admin-core#41]
现在rpc 的一些proto文件定义自已维护显得比较困难
发现ent的插件生态可以集成proto的generate
如果可以通过自定义的template，生产一些curd的logic，岂不美哉😄

[protoc-gen-entgrpc 参考](https://github.com/ent/contrib/tree/master/entproto/cmd/protoc-gen-entgrpc/template)

**Comment by suyuan32** [comment]
赶紧贡献代码呀，看了下你写的挺好的，参考了下你的代码 :)

**Comment by suyuan32** [comment]
@waltcow

**Comment by suyuan32** [comment]
最近还更新了 Ent 的中文文档 https://suyuan32.github.io/ent-chinese-doc/#/zh-cn/getting-started

**Comment by suyuan32** [comment]
入坑了

**Comment by waltcow** [comment]
哥们可以留个wechat吗，我的是我github的🆔

**Comment by suyuan32** [comment]
加你了@waltcow

**Comment by waltcow** [comment]
最近还在折腾了swagger,  不再需要生成swagger的注解了，
参考 `https://github.com/zeromicro/goctl-swagger` , 
直接在gogen 的时候，用api的spec生成好 swagger 的 json doc，
还有swagger-ui的集成和route 注册

后面还想拓展api的语法，api spec 支持errorResp的定义，参考这个(https://github.com/zeromicro/goctl-swagger/pull/55)

生产types的同时把errorType也一并生成
