### ISSUE TITLE
ent版本 postgresql 菜单管理报错

### ISSUE THREAD

**Issue by deegar** [suyuan32/simple-admin-core#51]
ent版本 postgresql 菜单管理报错！
错误大意：[must appear in the GROUP BY clause or be used in an aggregate function] 
忘记保存了 ，可以看看！

**Comment by suyuan32** [comment]
数据库什么版本？
![image](https://user-images.githubusercontent.com/21239039/208055375-1bd19aa1-f43b-454c-9348-0df4b28b382a.png)
目前最高只能到14

**Comment by suyuan32** [comment]
@deegar

**Comment by deegar** [comment]
psql (PostgreSQL) 14.5 (Debian 14.5-1.pgdg110+1)

**Comment by suyuan32** [comment]
ok,我到时候测试下

**Comment by suyuan32** [comment]
@deegar 已修复， pagination 的问题

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/208220906-1c8308a9-316f-4a34-a931-5c727ddfbe24.png)
现在 page 的 order 这样用
https://simpleadmin.ryansu.pro/#/simple-admin/zh-cn/docs/ent
