### ISSUE TITLE
关于postgresql的一点点建议

### ISSUE THREAD

**Issue by deegar** [suyuan32/simple-admin-core#53]
我看到您将pgsql的链接方式写法改了一下
`	//return fmt.Sprintf("postgresql://%s:%s@%s/%s?sslmode=%s", c.Username, c.Password, c.Host, c.DBName, c.SSLMode)

	return fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%d sslmode=%s", c.Host, c.Username, c.Password,
		c.DBName, c.Port, c.SSLMode)`

按照您更改的这种方式，那么在config文件中定义的port字段（如果端口不是5432的话就需要更改host值）就失去了意义！
建议还是维持更新前的写法！

纯属个人建议！

**Comment by suyuan32** [comment]
加上去了，旧的dsn 连上去数据库好像有点问题，还是用新的吧
![image](https://user-images.githubusercontent.com/21239039/208222914-4c702dfe-e1c1-4ff0-9d5c-3d4fc95feef5.png)
@deegar
