### ISSUE TITLE
Split proto file

### ISSUE THREAD

**Issue by anhhd2703** [suyuan32/simple-admin-core#55]
**Describe the bug**
Can't split core.proto to small file

**To Reproduce**

1. Try to split core.proto to core_1.proto and core_2.proto then import core_2 into core_1
2.  run command : "make gen-rpc"
3. throw error : "line xxx, request type must defined in core_1.proto"

**Expected behavior**
Split file proto like goctl

**Comment by suyuan32** [comment]
https://go-zero.dev/docs/goctl/zrpc/#proto-import

![image](https://user-images.githubusercontent.com/21239039/210677324-7053674f-e9ed-4a32-b322-25c92e322317.png)
![image](https://user-images.githubusercontent.com/21239039/210677344-1fc681f4-c45d-44f6-bd0c-ef04dd222914.png)

https://github.com/zeromicro/go-zero/issues/825

Only messages can be import. Do you test on original goctl? The goctls' behavior should be the same as goctl's. @anhhd2703

**Comment by anhhd2703** [comment]
> https://go-zero.dev/docs/goctl/zrpc/#proto-import
> 
> ![image](https://user-images.githubusercontent.com/21239039/210677324-7053674f-e9ed-4a32-b322-25c92e322317.png) ![image](https://user-images.githubusercontent.com/21239039/210677344-1fc681f4-c45d-44f6-bd0c-ef04dd222914.png)
> 
> [zeromicro/go-zero#825](https://github.com/zeromicro/go-zero/issues/825)
> 
> Only messages can be imported. Do you test on original goctl? The goctls' behavior should be the same as goctl's. @anhhd2703

oh. my mistake. Thanks for helping me!

**Comment by suyuan32** [comment]
We now support splitting proto files @anhhd2703 
https://doc.ryansu.pro/guide/quick-start/codegen/rpc_example.html

Just put proto files in desc directory, goctls will merge them automaticly.

See https://github.com/suyuan32/simple-admin-core/tree/master/rpc/desc

**Comment by anhhd2703** [comment]
@suyuan32  thank you very much.
It's sounds good to break file and easy to control.
