### ISSUE TITLE
mysql初始化问题

### ISSUE THREAD

**Issue by YF-Gooo** [suyuan32/simple-admin-core#60]
您好，ent是自动生成table吗？有sql文件吗？
我启动rpc以后也没有生成新的表格。有具体初始化数据库的文档吗？

**Comment by suyuan32** [comment]
> 您好，ent是自动生成table吗？有sql文件吗？
> 我启动rpc以后也没有生成新的表格。有具体初始化数据库的文档吗？
> 

https://doc.ryansu.pro/guide/basic-config/env_setting


不需要sql文件，看文档

**Comment by YF-Gooo** [comment]
可以了，谢谢~
