### ISSUE TITLE
启动找不到配置文件

### ISSUE THREAD

**Issue by AzraelJi** [suyuan32/simple-admin-core#64]
1、latest版本
2、run err：
2023/02/02 10:28:22 error: config file etc/core.yaml, open etc/core.yaml: no such file or directory
3、源代码：
var configFile = flag.String("f", "etc/core.yaml", "the config file")
4、修改成：
var configFile = flag.String("f", "api/etc/core.yaml", "the config file")
可以成功启动

**Comment by suyuan32** [comment]
一般都是在api目录下启动，你可以直接使用 -f 参数指定路径 
查看文档 https://doc.ryansu.pro/zh/guide/basic-config/env_setting.html

**Comment by AzraelJi** [comment]
谢谢
