### ISSUE TITLE
登录时候显示用户无权限访问此接口

### ISSUE THREAD

**Issue by YF-Gooo** [suyuan32/simple-admin-core#69]
大佬，最新的代码，点击登录后，弹出用户无权限访问此接口，错误是/sys-api/user/info这个接口返回的。
是不是ent schema哪里没有导入数据了?我看casbin admin有权限访问这个接口啊。我是整个项目重新拉了跑了下，应该没有操作问题

**Comment by suyuan32** [comment]
> 大佬，最新的代码，点击登录后，弹出用户无权限访问此接口，错误是/sys-api/user/info这个接口返回的。
> 是不是ent schema哪里没有导入数据了?我看casbin admin有权限访问这个接口啊。我是整个项目重新拉了跑了下，应该没有操作问题
> 
> 

得删掉数据库重新初始化

**Comment by YF-Gooo** [comment]
> 重新初始化

我数据库也删了，重新建表的。还是不行（哭）

**Comment by suyuan32** [comment]
> > 重新初始化
> 
> 我数据库也删了，重新建表的。还是不行（哭）

重启api了吗？

**Comment by YF-Gooo** [comment]
> > > 重新初始化
> > 
> > 
> > 我数据库也删了，重新建表的。还是不行（哭）
> 
> 重启api了吗？@YF-Gooo

嗯嗯嗯，可以了。感谢感谢，刚刚只重启了rpc，我忘了casbin是api去查的
