### ISSUE TITLE
swagger generated fail!

### ISSUE THREAD

**Issue by anhhd2703** [suyuan32/simple-admin-core#70]
**Describe the bug**
I try with the latest version.

**To Reproduce**
1. run "make gen-api"
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/54494592/218697287-0e1dd4f2-e276-4af6-a4b9-71ebd671641d.png)
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/54494592/218697546-c4962823-a57a-499d-b635-c611196c7e59.png">

**Comment by anhhd2703** [comment]
@suyuan32  could you help me pls ?

**Comment by suyuan32** [comment]
update go swagger to latest @anhhd2703

**Comment by suyuan32** [comment]
install v0.30.4

**Comment by suyuan32** [comment]
go install github.com/go-swagger/go-swagger/cmd/swagger@latest

**Comment by suyuan32** [comment]
@anhhd2703

**Comment by anhhd2703** [comment]
@suyuan32 thanks
