### ISSUE TITLE
执行goctls rpc new example生成文件依赖爆红

### ISSUE THREAD

**Issue by priceou** [suyuan32/simple-admin-core#80]
根目录执行goctls rpc new example --ent=true  --port=9015  --desc=true
拉的最新的simple-admin-core和simple-admin-tool
1.生成的/example/internal/config/config.go中
`import (
	"github.com/suyuan32/simple-admin-core/pkg/config"

	"github.com/zeromicro/go-zero/core/stores/redis"
	"github.com/zeromicro/go-zero/zrpc"
)`
github.com/suyuan32/simple-admin-core/pkg/config爆红
rpc下的相同位置引用的是github.com/suyuan32/simple-admin-common/config

3.文档中说goctls指令的go_zero_version和tool_version参数都是必须的，但是不添加也能执行

**Comment by suyuan32** [comment]
已修复，生成文件的bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月15日(周三) 下午3:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [suyuan32/simple-admin-core] 执行goctls rpc new example生成文件依赖爆红 (Issue #80)




 
根目录执行goctls rpc new example --ent=true  --port=9015  --desc=true
 拉的最新的simple-admin-core和simple-admin-tool
 1.生成的/example/internal/config/config.go中
 `import (
 "github.com/suyuan32/simple-admin-core/pkg/config"
 "github.com/zeromicro/go-zero/core/stores/redis" "github.com/zeromicro/go-zero/zrpc"  
)`
 github.com/suyuan32/simple-admin-core/pkg/config爆红
 rpc下的相同位置引用的是github.com/suyuan32/simple-admin-common/config
 
3.文档中说goctls指令的go_zero_version和tool_version参数都是必须的，但是不添加也能执行

**Comment by suyuan32** [comment]
@priceou  下载最新代码重新编译下 goctls
