### ISSUE TITLE
源码中的/rpc/ent/pagination.go不会通过gen-ent生成吗

### ISSUE THREAD

**Issue by priceou** [suyuan32/simple-admin-core#81]
通过goctls创建的RPC 基本项目
在通过go generate生成了/ent下的的文件后
缺少类似pagination.go的还有not_empty_update.go

导致生成的逻辑代码中l.svcCtx.DB.Student.Query().Where(predicates...).Page(l.ctx, in.Page, in.PageSize)用不了
`
err := l.svcCtx.DB.Student.UpdateOneID(in.Id).
		SetNotEmptyName(in.Name).
		SetNotEmptyAge(int(in.Age)).
		Exec(l.ctx)
`
中SetNotEmptyName，SetNotEmptyAge方法也没有

**Comment by suyuan32** [comment]
生成有的，创建项目就带有了, 
![image](https://user-images.githubusercontent.com/21239039/225264743-0e32003d-9830-4900-a216-bffb24332a2a.png)
如果你是说下面这几个标红的话本来就是不支持的，只是生成给大家展示用， 看下规范 http://localhost:8080/zh/guide/basic-config/standard.html

**Comment by suyuan32** [comment]
SetNotEmpty 只支持 string 和 int - float 类型，对于bool只能使用 Set

**Comment by suyuan32** [comment]
@priceou

**Comment by priceou** [comment]
> 生成有的，创建项目就带有了, ![image](https://user-images.githubusercontent.com/21239039/225264743-0e32003d-9830-4900-a216-bffb24332a2a.png) 如果你是说下面这几个标红的话本来就是不支持的，只是生成给大家展示用， 看下规范 http://localhost:8080/zh/guide/basic-config/standard.html

那这个.Page()方法找不到的问题该如何解决

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/225266015-7658fce9-e50a-4657-b96e-e8896562c8dd.png)
检查下是否有pagination.tmpl

**Comment by suyuan32** [comment]
有的话直接make gen-ent

**Comment by priceou** [comment]
> 有的话直接make gen-ent

能不能在执行goctls rpc new example时自动生成相应的*.tmpl文件？

**Comment by suyuan32** [comment]
生成有的，你是在什么系统下？ linux可以的, windows 得测试下

**Comment by suyuan32** [comment]
目前建议在wsl下开发先，windows下有bug

**Comment by suyuan32** [comment]
> > 生成有的，你是在什么系统下？ linux可以的, windows 得测试下
> 
> 我是windows系统，没有生成这2个文件 ![image](https://user-images.githubusercontent.com/16974926/225267226-7fec5b3e-add6-40ea-a77e-f1adde4fb45f.png)

@priceou https://doc.ryansu.pro/zh/guide/FAQ.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-windows-%E7%8E%AF%E5%A2%83

**Comment by suyuan32** [comment]
我测试了下在windows 下是能生成的，新增文档，你可以看下
