### ISSUE TITLE
*.api文件可以自动生成吗

### ISSUE THREAD

**Issue by priceou** [suyuan32/simple-admin-core#82]
参照官方的https://doc.ryansu.pro/zh/guide/quick-start/codegen/rpc_example.html
生成rpc微服务的代码后
我想基于源码直接添加example相关接口到/api下，而不是新建一个api项目，目前有办法做到吗
我有试过直接运行goctls api proto，报没有.api文件的错误

**Comment by suyuan32** [comment]
https://doc.ryansu.pro/zh/guide/quick-start/codegen/api_example.html

**Comment by suyuan32** [comment]
不理解，本来goctls api proto就可以在任何api服务生成 @priceou

**Comment by suyuan32** [comment]
具体要做什么？

**Comment by priceou** [comment]
> 不理解，本来goctls api proto就可以在任何api服务生成 @priceou
运行goctls api proto不是需要相应的example.api文件吗，这个example.api文件也是通过goctls生成的吗？

**Comment by priceou** [comment]
> 具体要做什么？

我想新增rpc微服务节点，但是我不想将新的api接口放到新的api服务里，而是想放到core对应的api服务里

**Comment by suyuan32** [comment]
自动生成的

> > 不理解，本来goctls api proto就可以在任何api服务生成 @priceou
> 
> 运行goctls api proto不是需要相应的example.api文件吗，这个example.api文件也是通过goctls生成的吗？

**Comment by suyuan32** [comment]
https://doc.ryansu.pro/zh/guide/quick-start/core/quick_develop_example.html#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%8F%91demo

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/225560968-3135fc24-7c80-499e-b284-1b5ef9f9f293.png)

**Comment by suyuan32** [comment]
@priceou 注意参数就行

**Comment by suyuan32** [comment]
job服务的API就是用命令生成的，接入了core，可以看看 @priceou

**Comment by priceou** [comment]
> job服务的API就是用命令生成的，接入了core，可以看看 @priceou

example.api文件是哪个指令生成的？不知道我是不是遇到bug了，没有生成

**Comment by suyuan32** [comment]
goctls api proto --proto=/home/ryan/GolandProjects/simple-admin-core/rpc/core.proto --api_service_name=core --rpc_service_name=Core --o=./ --model=Department --rpc_name=Core --grpc_package=github.com/suyuan32/simple-admin-core/rpc/types/core

**Comment by suyuan32** [comment]
生成的是department.api

**Comment by suyuan32** [comment]
你尝试过example 了吗？完整走一遍example api 项目看看生成了什么

**Comment by suyuan32** [comment]
https://github.com/suyuan32/simple-admin-example-api
