### ISSUE TITLE
请问 roleId 是在什么地方写入到ctx中的呢？

### ISSUE THREAD

**Issue by coder2z** [suyuan32/simple-admin-core#87]
roleId ：
<img width="948" alt="image" src="https://user-images.githubusercontent.com/40028336/227962080-f2dc13ff-959e-473f-86fb-f771b0f586b7.png">
token_ 的写入我也只看到更新用户信息的时候才写入：
<img width="860" alt="image" src="https://user-images.githubusercontent.com/40028336/227962263-6262baf1-bb7a-497f-8041-9740fa3eec81.png">

看了下源码 总感觉代码不全呢

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/227964316-7f947e01-c707-4e28-afda-8676a7008485.png)

**Comment by suyuan32** [comment]
token是黑名单，拉黑才写入

**Comment by coder2z** [comment]
我看过这里这里是直接写入到 数据库里，没有看到写入到redis里面。

**Comment by suyuan32** [comment]
额，代码里有的，找找

**Comment by coder2z** [comment]
> 额，代码里有的，找找

好的我再看看

**Comment by coder2z** [comment]
> > 如果token是黑名单，拉黑才写入的话，请问下这里登录校验是在哪里做的呢？
> 
> go zero实现了，看go zero官方文档 jwt

好的了解了，但是roleId的写入还是没找到 难道也是框架层做了 ？

**Comment by coder2z** [comment]
> > > 如果token是黑名单，拉黑才写入的话，请问下这里登录校验是在哪里做的呢？
> > 
> > 
> > go zero实现了，看go zero官方文档 jwt
> 
> 好的了解了，但是roleId的写入还是没找到 难道也是框架层做了 ？

找到了。写的有点隐蔽，藏到了jwt里面，go-zero 解析了

**Comment by suyuan32** [comment]
> https://github.com/suyuan32/simple-admin-core/blob/master/api/internal/logic/user/login_logic.go

roleid不是已经图片了吗？ newjwttoken的参数不就是

**Comment by coder2z** [comment]
还有最后一个问题，现在我看 国际化是写到 一个json文件中的 但是url 描述 和 一些管理的字段也有涉及到国际化。

但是这些管理大部分都是会在使用中 动态创建的，这样就必须更新 国际化文件（json），这是需要重启服务的，这一点是不是有点不合理呢？

**Comment by suyuan32** [comment]
json目前只用在更新不频繁的字段，有优化的空间，可以将文件动态挂载，主流方案还是文件形式，后期可以优化下

**Comment by suyuan32** [comment]
本地翻译速度才能保证，如果存到数据库，数据一多查询过于频繁，会卡死的，存在redis中也有调用过多问题，几千条数据每个都查询也不靠谱，只有系统核心的数据才需要国际化，其他数据不建议使用国际化，直接存对应的语言

**Comment by coder2z** [comment]
其实也有一些其他方案，就比如把全部都load 到内存，内存查询的话就很快了。

数据放在db 

服务里面起一个timer 去刷新 内存数据即可。

因为这种其实时效性也能接受，也可以加一个强制刷新 api

**Comment by suyuan32** [comment]
也可以的，可以优化，你也可以贡献代码改进下
