### ISSUE TITLE
desc的merge功能能否添加map支持？

### ISSUE THREAD

**Issue by crazy6995** [suyuan32/simple-admin-core#89]
一些接口需使用动态参数，proto可支持map，但使用merge后，map丢失，且生成的文件也有一些问题。

示例:

```
message SMSCodeReq {
  string phone_number = 1;
  string type = 2;
  string provider_name = 3;
  map<string, string> parameters = 4;
}
```

看了一下源码，使用了 `parser#Parse` 方法去逐个`parse` `.proto` 文件，然后使用 stringBuilder 构造最终merge后的文件。

在处理 `message` 时，使用了`protox.MessageVisitor`。 `protox.ProtoField.Type` 似乎并不能正确取到 map 的类型，这里没有仔细研究应该怎么处理。。。

**Comment by crazy6995** [comment]
看样子应该要自定义 mapVisitor，实现 `Visitor#VisitMapField` 接口以便于可读取到mapField的值。 protox中的MessageVisitor默认只实现了 NormalField 的处理方法

**Comment by crazy6995** [comment]
初步实现方案，为MessageVisitor添加方法 `VisitMapField` 并读取 Name与Type， map类型不能使用 `repeated` 与 `optional`，故此默认false即可


```
func (m MessageVisitor) VisitMapField(i *proto.MapField) {
	ProtoField.Name = i.Field.Name
	ProtoField.Type = fmt.Sprintf("map<%s,%s>", i.KeyType, i.Field.Type)
	ProtoField.Repeated = false
	ProtoField.Optional = false
}
```

**Comment by suyuan32** [comment]
你可以先实现下，之前就有人提过了，或者我过段时间再修复一下

**Comment by crazy6995** [comment]
ok ， 我待会儿提一个pr。 

![image](https://user-images.githubusercontent.com/5605020/230067021-4782adad-efa9-4bef-8e5e-0902a80a71d7.png)

另外，不知道这个地方为什么使用 index ， 从field中是可以提取到 sequence 的，使用 `index` 会破坏原有的字段顺序。

**Comment by suyuan32** [comment]
是吗？之前没注意到，如果有的话就用sequence

**Comment by crazy6995** [comment]
> 是吗？之前没注意到，如果有的话就用sequence

@suyuan32 

https://github.com/suyuan32/simple-admin-tools/pull/42
