### ISSUE TITLE
mac M1 使用make docker构建时，一直提示does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8

### ISSUE THREAD

**Issue by franktrue** [suyuan32/simple-admin-core#97]
**Describe the bug**
failed to get destination image "sha256:XXX": image with reference sha256:XXX was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8

**To Reproduce**
1. 修改dockerfile中FROM --platform=linux/amd64 XXX
2. 修改makefile中docker build --no-cache --platform linux/amd64 XXX
3. 执行make docker
4. 报错如上

**Expected behavior**
不修改的话打包的镜像无法在服务器端使用，报错：standard_init_linux.go:228: exec user process caused: exec format error

**Screenshots**
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/10108380/234241885-fda6c7d9-e18f-447a-a9ca-1a259b9726da.png">

**Comment by suyuan32** [comment]
你是用mac做服务器？

**Comment by franktrue** [comment]
不是，在mac端使用默认make docker打包镜像并上传至仓库，在服务器端（Centos）引用镜像，会报错：standard_init_linux.go:228: exec user process caused: exec format error

**Comment by suyuan32** [comment]
看报错是amd和arm不兼容，最后搞定了吗？

**Comment by suyuan32** [comment]
他的意思是你在arm平台构建的镜像无法在amd的linux下运行

**Comment by suyuan32** [comment]
建议直接在服务器构建或amd的机器

**Comment by franktrue** [comment]
嗯嗯，好的，谢谢，正在尝试docker buildx 不过还没成功
